# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
  - dev
  - qa
  - uat
  - staging
  - prod

resources:
- repo: self

variables:
 - name: dockerRegistryServiceConnection
   value: '805e423a-a0e7-41c8-a8e7-a1828d65300d'
 - name: imageRepository
   value: 'users-microservice' 
 - name: containerRegistry
   value: 'akshatecommerceregistry.azurecr.io' 
 - name: dockerFilePath
   value: '$(Build.SourcesDirectory)/ECommerceAppAPI/Dockerfile' 
 - name: tag
   value: '$(Build.BuildId)'
 - name: vmImageName
   value: 'ubuntu-latest' 
 - name: windowsImageName
   value: 'windows-latest'
 - name: aksClusterName
   value: 'ecommerce-aks-cluster'  
 - name: aksServiceConnectionName
   value: 'aks-deploy-connection'
 - name: deploymentFile
   value: '$(Build.SourcesDirectory)/k8s/users-microservice-deployment.yml' 

stages:
 - stage: Build
   displayName: Build and push stage
   jobs:
   - job: Build
     displayName: Docker Build
     pool:
      vmImage: $(vmImageName)
     steps:
     - task: Docker@2
       displayName: Build and push an image to ecommerce registry
       inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerFilePath)
        buildContext: $(Build.SourcesDirectory)     
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(tag)

 - stage: Test
   displayName: Test and publish results stage
   jobs:
   - job: RunTest
     displayName: Running Unit Tests
     pool: 
      vmImage: $(windowsImageName)
     steps:
      - checkout: self
        displayName: Checkout source code

      - task: NuGetToolInstaller@1
        displayName: Install NuGet Tool
  
      - task: NuGetCommand@2
        displayName: Restore Nuget Packages
        inputs:
         command: 'restore'
         restoreSolution: '**/*.sln'

      - task: MSBuild@1
        displayName: Build Solution
        inputs:
         solution: '**/*.sln'
         msbuildArchitecture: 'x64'
         platform: 'Any CPU'
         configuration: 'Debug'

      - task: VSTest@3
        displayName: Test Solution
        inputs:
         testSelector: 'testAssemblies'
         testAssemblyVer2: |
          **\UsersUnitTests.dll
          !**\*TestAdapter.dll
          !**\obj\**
         searchFolder: '$(System.DefaultWorkingDirectory)'
         runTestsInIsolation: true
         codeCoverageEnabled: true

 - stage: DeployToDev
   displayName: Deploy to Dev 
   dependsOn: Test
   condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'],'refs/heads/dev'))
   jobs:
   - template: deploy-job-template.yml
     parameters:
      namespace: ecommerce-dev

 - stage: DeployToQA
   displayName: Deploy to QA
   dependsOn: Test
   condition: and(succeeded(), eq(variables['Build.SourceBranch'],'refs/heads/qa'))
   jobs:
   - template: deploy-job-template.yml
     parameters:
      namespace: ecommerce-qa

 - stage: DeployToUAT
   displayName: Deploy to UAT
   dependsOn: Test
   condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'],'refs/heads/uat'))
   jobs:
   - template: deploy-job-template.yml
     parameters:
      namespace: ecommerce-uat

 - stage: DeployToStaging
   displayName: Deploy to Staging
   dependsOn: Test
   condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'],'refs/heads/staging'))
   jobs:
   - template: deploy-job-template.yml
     parameters:
      namespace: ecommerce-staging

 - stage: DeployToProd
   displayName: Deploy to Prod
   dependsOn: Test
   condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'],'refs/heads/prod'))
   jobs:
   - template: deploy-job-template.yml
     parameters:
      namespace: ecommerce-prod